# Jekyll Configuration
title: Blog Saya
description: Blog pribadi saya tentang perjalanan
url: "https://username.github.io"  # Ganti dengan URL repositori GitHub Pages Anda
baseurl: ""  # Jika menggunakan subdirektori, sesuaikan

# Tambahkan custom stylesheet
sass:
  style: compressed

# Menyertakan CSS kustom
include:
  - _posts
  - custom.css  # Menyertakan file custom.css

# Optional: Jika Anda ingin menambahkan lebih banyak file ke dalam output
exclude:
  - README.md
